services:

  nodeapp:
    image: basic-express-app
    container_name: my-express-app-2
    ports:
      - "3001:3000"
    environment:
      - MONGO_URL=mongodb://mongo:27017/mongodb
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
      - mongodb
      - mongo-express

  redis:
    image: redis:latest
    container_name: redis_2
    ports:
      - "6380:6379"

  mongodb:
    image: mongo:latest
    container_name: mongo_1
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=pass
    ports:
      - "27017:27017"


  mongo-express:
      image: mongo-express:latest
      restart: always
      container_name: mongo-express
      environment:
        - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
        - ME_CONFIG_MONGODB_ADMINPASSWORD=password
        - ME_CONFIG_MONGODB_SERVER=mongodb
      ports: 
        - "8081:8081"


# services:
#   app:
#     image: basic-express-app
#     container_name: express-app-server-2
#     ports:
#       - '5001:3000'
#     environment:
#       - NODE_ENV=development
#       - MONGO_URL=mongodb://mongo:27017/mongodb
#       - REDIS_URL=redis://redis:6379
#     depends_on:
#       - mongodb
#       - redis
#       - mongo-express
#   # mongodb container
#   mongodb:
#     image: mongo:latest
#     container_name: mongo-1
#     ports:
#       - "27017:27017"
#     environment:
#       - MONGO_INITDB_ROOT_USERNAME=admin
#       - MONGO_INITDB_ROOT_PASSWORD=password
#     # volumes:
#     #   - ./mongo-data:/data/db
#   # mongo-express container
#   mongo-express:
#     image: mongo-express:latest
#     container_name: mongo-express
#     restart: always
#     ports:
#       - "8081:8081"
#     environment:
#       - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
#       - ME_CONFIG_MONGODB_ADMINPASSWORD=password
#       - ME_CONFIG_MONGODB_SERVER=mongodb
#   # redis container
#   redis:
#     image: redis:latest
#     container_name: redis-2
#     ports:
#       - "6380:6379"