version: '1'

services:
  redis:
    image: redis:alpine
    container_name: redis_2
    ports:
      - "6380:6379"

  mongodb:
    image: mongo
    container_name: mongo_1
    restart: always
    ports:
      - "27017:27017"


  mongo-gui:
      image: mongo-express
      restart: always
      container_name: mongo_express
      ports: 
        - "8081:8081"